import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parsePlainLyrics,timingUnits,stampTiming,timedLyricRows,exportLrc,parseLyrics,draftFromLyric,authoring,example,normalizeProject,validate} from '../docs/core.mjs';
import {STRINGS,setLocale,t,localizeError} from '../docs/i18n.mjs';
let rows=parsePlainLyrics('\uFEFF が、きゃー！\r\nまたね。');
assert.deepEqual(rows[0].tokens.map(t=>t.text),['が','き','ゃ','ー']);
assert.equal(timingUnits('か\u3099')[0].text,'か\u3099');
assert.equal(timingUnits('𠮷、😀あ')[1].offset,5);
assert.throws(()=>parsePlainLyrics('…'),/文字/);
assert.equal(parsePlainLyrics('…','line')[0].text,'…');
assert.throws(()=>stampTiming(rows,0,0,-1,30));
assert.throws(()=>stampTiming(rows,0,0,30,30));
assert.throws(()=>timedLyricRows(rows,'character',30),/未記録/);
let sec=2.1;
for(let r=0;r<rows.length;r++)for(let c=0;c<rows[r].tokens.length;c++){const original=structuredClone(rows);rows=stampTiming(rows,r,c,sec,30);assert.equal(original[r].tokens[c].time,null);sec+=.5;}
const text=exportLrc(rows,'character',30),roundtrip=parseLyrics(text);
assert.deepEqual(roundtrip.map(r=>r.text),rows.map(r=>r.text));
assert.deepEqual(roundtrip.map(r=>r.tokens.map(t=>[t.time,t.offset])),rows.map(r=>r.tokens.map(t=>[t.time,t.offset])));
assert.deepEqual(draftFromLyric(roundtrip[0],roundtrip[1].time,30,'ja').map(n=>n.kana),['が','き','ゃ','ー']);
const invalid=structuredClone(rows);invalid[0].tokens[2].time=1;assert.throws(()=>exportLrc(invalid,'character',30),/逐字時刻/);
const line=parsePlainLyrics('あ\nい','line').map((r,i)=>({...r,time:2.1+i}));
assert.equal(exportLrc(line,'line',30),'[00:02.100]あ\n[00:03.100]い\n');
assert.throws(()=>exportLrc([line[1],line[0]],'line',30),/行時刻/);
const en=parsePlainLyrics("Hello, don't stop!",'character');sec=2.1;for(let c=0;c<en[0].tokens.length;c++){en[0].tokens[c].time=sec;sec+=.1;}
const enNotes=draftFromLyric(parseLyrics(exportLrc(en,'character',30))[0],8,30,'en');
assert.deepEqual(enNotes.map(n=>n.kana),['Hello',"don't",'stop']);assert.equal(enNotes[1].time,2.6);
assert.deepEqual(timingUnits('Hello world','word').map(t=>t.text),['Hello','world']);
const mixed=parseLyrics('[00:02.100]<00:02.100>恋<00:03.100>の<00:04.100>Love')[0];
assert.throws(()=>draftFromLyric(mixed,8,30,'ja'),/発音/);
assert.deepEqual(draftFromLyric({...mixed,reading:'こいのらぶ'},8,30,'ja').map(n=>n.kana),['こ','い','の','ら','ぶ']);
const p=example();p.lyricTiming={mode:'character',rows};p.chart.lyrics=timedLyricRows(rows,'character',30);
assert.deepEqual(normalizeProject(p).lyricTiming,p.lyricTiming);
assert.deepEqual(authoring(p).lyrics,rows.map(r=>({time:r.tokens[0].time,text:r.text})));
const malformed=structuredClone(p);malformed.lyricTiming.rows[0].tokens[1].offset=0;assert.throws(()=>normalizeProject(malformed),/構造/);
const same=parsePlainLyrics('あい');same[0].tokens.forEach(t=>t.time=2.117);same[0].time=2.117;
const notes=draftFromLyric(timedLyricRows(same,'character',30)[0],8,30,'ja');p.chart.notes=notes;
assert.ok(validate(authoring(p),p.meta).some(e=>e.includes('同じ 30 Hz tick')));
const html=await readFile(new URL('../docs/index.html',import.meta.url),'utf8');
for(const key of [...html.matchAll(/data-i18n(?:-aria-label|-placeholder)?="([^"]+)"/g)].map(m=>m[1]))assert.ok(STRINGS[key],key);
for(const [key,translations] of Object.entries(STRINGS))for(const lang of ['ja','zh','en'])assert.equal(typeof translations[lang],'string',key+':'+lang);
setLocale('en');assert.match(localizeError('未記録の行・文字があります'),/untimed/i);setLocale('zh');assert.match(t('lineMode'),/逐句/);assert.match(localizeError(' 難度が不正'),/难度/);
console.log('PASS: graphemes; punctuation-preserving Enhanced LRC roundtrip; line/word timing; time bounds/order; EN whole-word initials; JA author readings; unchanged pack lyrics; 30 Hz collision checks; draft persistence; trilingual UI keys.');
